personal_portfolio/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.all_blogs, name = 'all_blogs'),
    path('<int:blog_id>/', views.detail, name = 'detail'),

]

personal_portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('blog/', include('blog.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

personal_portfolio/blog/models.py
"""Modelos 
de Blog
"""
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateField()
    description = models.TextField()

personal_portfolio/portfolio/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

personal_portfolio/blog/views.py
"""Views de 
blog
"""
from django.shortcuts import render, get_object_or_404
from .models import Post

def all_blogs(request):
    posts = Post.objects.all()
    return render(request, 'blog/blogs.html', {'posts': posts})

def detail(request, blog_id):
    blog = get_object_or_404(Post, pk= blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

personal_portfolio/portfolio/views.py
"""View de la página inicial"""
from django.shortcuts import render
from portfolio.models import Project

# Create your views here.
def home(request):
    """Se llaman a los objetos dentro del modelo Project"""
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects':projects})

personal_portfolio/blog/templates/blog/blogs.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>DIMM BLOG</title>
</head>
<body>
  <h1>DIMM BLOG</h1>
  {% for post in posts %}
  <a href="{% url 'blog:detail' post.id %}"><h2>{{ post.title }}</h2></a>
  <h5>{{ post.date }}</h5>
  <p>{{ post.description }}</p>
  {% endfor %}
</body>
</html>

personal_portfolio/blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>{{ blog.title }}</h1>
</body>
</html>

personal_portfolio/portfolio/templates/portfolio/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="./style.css">
  <title>Portfolio DIMM</title>

</head>
<body>
 {% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="#">
    <img src="/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">DIMM</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Inicio <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% static 'portfolio/DIPLOMA_INTRODUCTION_TO_CLOUD_COMPUTING.pdf' %}">Curriculum</a>
      <a class="nav-item nav-link" href="#">Blog</a>
      <a class="nav-item nav-link disabled" href="#">Linkedin</a>
    </div>
  </div>
</nav>

  <h1 class="text-center">Un porfolio dice más que mil curriculums</h1>
  <div class="container">
    <img src="{% static 'portfolio/Ivan1.jpg' %}" class="img-fluid rounded" alt="Responsive image" id="ivanphoto">
  </div>
  
  {% for project in projects %}

  <h2>{{ project.title }}</h2>
  <p>{{ project.description }}</p>
  <img src="{{ project.image.url }}" alt="">
  {% if project.url %}
  <a href="{{ project.url }}">Link</a>
  {% endif %}
  {% endfor %}
</body>
</html>